#!/bin/bash
#
# Copyright 2011-2014 NimbusKit
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

WRITE_ACCESS_BASE_URL="git@github.com:NimbusKit/"
READ_ONLY_BASE_URL="https://github.com/NimbusKit/"

if grep -Fq "url = git@github.com:NimbusKit/Catalog.git" .git/config
then
  BASE_URL=$WRITE_ACCESS_BASE_URL
else
  BASE_URL=$READ_ONLY_BASE_URL
fi

build_doxygen() {
  repo="${BASE_URL}doxygen.git"

  if ! ls doxygen 1>/dev/null 2>/dev/null; then
    echo "Cloning doxygen..."
    git clone $repo doxygen
    echo "Done"
  fi

  pushd doxygen
  ./configure
  make
  sudo make install
  popd
}

if ! doxygen -v 1>/dev/null 2> /dev/null; then
  build_doxygen
fi

doxygen docs/Doxyfile
open docs/output/html/index.html
