#!/bin/bash
#
# Copyright 2011-2014 NimbusKit
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

commit_feature() {
  reponame=$1
  foldername=$(echo $1| tr '[:upper:]' '[:lower:]')
  featurefolder="features/$foldername"

  echo
  echo "Status of $reponame"
  pushd $featurefolder > /dev/null
  git add .
  git commit -a
  popd > /dev/null
}

commit_feature Actions
commit_feature AttributedLabel
commit_feature Badge
commit_feature Core
commit_feature SnapshotRotation
commit_feature Tables
