#!/bin/bash
#
# Copyright 2011-2014 NimbusKit
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

status_of_feature() {
  reponame=$1
  foldername=$(echo $1| tr '[:upper:]' '[:lower:]')
  featurefolder="features/$foldername"

  echo
  echo "Status of $reponame"
  pushd $featurefolder > /dev/null
  git status
  popd > /dev/null
}

status_of_feature Actions
status_of_feature AttributedLabel
status_of_feature Badge
status_of_feature Collections
status_of_feature Core
status_of_feature Interapp
status_of_feature NetworkImage
status_of_feature Overview
status_of_feature SnapshotRotation
status_of_feature Tables
status_of_feature TextField
status_of_feature WebController

echo
echo "Status of Catalog + Framework"
git status
