#!/bin/bash
#
# Copyright 2011-2014 NimbusKit
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

mkdir -p features

WRITE_ACCESS_BASE_URL="git@github.com:NimbusKit/"
READ_ONLY_BASE_URL="https://github.com/NimbusKit/"

if grep -Fq "url = git@github.com:NimbusKit/Catalog.git" .git/config
then
  BASE_URL=$WRITE_ACCESS_BASE_URL
else
  BASE_URL=$READ_ONLY_BASE_URL
fi

refresh_feature() {
  reponame=$1
  foldername=$(echo $1| tr '[:upper:]' '[:lower:]')
  repo="${BASE_URL}$reponame.git"
  featurefolder="features/$foldername"

  if ! ls $featurefolder 1>/dev/null 2>/dev/null; then
    echo "Cloning $reponame..."
    git clone $repo $featurefolder
    echo "Done"
  else
    pushd $featurefolder 1>/dev/null
    echo "Fetching latest $reponame commits..."
    git fetch
    popd 1>/dev/null
  fi
}

refresh_feature Actions
refresh_feature AttributedLabel
refresh_feature Badge
refresh_feature Collections
refresh_feature Core
refresh_feature Interapp
refresh_feature NetworkImage
refresh_feature Overview
refresh_feature PagingScrollView
refresh_feature Photos
refresh_feature SnapshotRotation
refresh_feature Tables
refresh_feature TextField
refresh_feature WebController

